{{- if .Values.dockerSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerSecret.name }}
  namespace: {{ include "python-app.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"%s\"}}}" .Values.dockerSecret.auth | b64enc | quote }}
{{- end}}