site_name: ${{ values.app_name }}
site_description: Documentation for the ${{ values.app_name }} project
repo_url: https://github.com/mmahabadi/${{ values.app_name }}

nav:
  - Home: index.md

plugins:
  - techdocs-core
